### ISSUE TITLE
Issue in loading all the spots

### ISSUE THREAD

**Issue by okazakib** [jfnavarro/st_viewer#43]
Hello,

After installing the latest version of ST_Viewer (0.8.1), I have been unable to load all the spots for a dataset on to the platform. I have tried this with several different datasets, but the issue remains the same. I have attached a screenshot for your reference. I am also unable to run the previous versions of the software.
<img width="1440" alt="Screenshot 2020-04-14 at 13 34 21" src="https://user-images.githubusercontent.com/64007874/80096336-b00e2a00-8569-11ea-9b80-1df7f22a064c.png">

**Comment by jfnavarro** [comment]
Hi! Could you tell me what OS and version are you using? You should be able to install and run previous versions but note that previous versions require R to be installed in the system and the R version must be the same as the one indicated in the release.

**Comment by okazakib** [comment]
Hello! 
I am using MacOS version 10.15.4 and R version 3.6.3. Should I use a previous version of R?

Thanks.

**Comment by jfnavarro** [comment]
MacOS Catalina as I expected. This problem is related to Catalina and it does not happen in previous versions of MacOS. I am working on it. Regarding older releases of the ST Viewer, the version 0.7.6 that you can find here (https://github.com/SpatialTranscriptomicsResearch/st_viewer/releases) should work with Catalina and R 3.6.3

**Comment by okazakib** [comment]
Thanks a lot. This works now.
